# -*- coding: utf-8 -*-
"""news analysis 2.0

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lQL0o1_d3utGCr83FOJwireh_iIKmG5i
!pip install yfinance pandas numpy scikit-learn transformers torch ta feedparser requests -q ipywidgets -q
"""


import yfinance as yf
import pandas as pd
import numpy as np
import ta
import torch
import feedparser
import requests
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from sklearn.ensemble import RandomForestClassifier
from concurrent.futures import ThreadPoolExecutor
from bs4 import BeautifulSoup
import requests
import ipywidgets as widgets
from IPython.display import display

def fetch_article_snippet(url):
    """
    Returns a short summary/snippet from the article page.
    Tries <meta name='description'> or first paragraph.
    """

    try:
        headers = {"User-Agent": "Mozilla/5.0"}
        res = requests.get(url, headers=headers, timeout=4)
        soup = BeautifulSoup(res.text, "html.parser")

        # Try meta description first
        desc = soup.find("meta", {"name":"description"})
        if desc and desc.get("content"):
            return desc.get("content")[:200] + "..."

        # Otherwise first paragraph
        p = soup.find("p")
        if p and p.text:
            return p.text[:200] + "..."

    except:
        pass

    return ""

print("Loading FinBERT...")
tokenizer = AutoTokenizer.from_pretrained("ProsusAI/finbert")
model_nlp = AutoModelForSequenceClassification.from_pretrained("ProsusAI/finbert")

# ============================================================
# GLOBAL IMPACT KEYWORDS
# ============================================================

HIGH_IMPACT = [
    "modi","nirmala","budget","rbi","interest rate",
    "inflation","fed","china","war","oil",
    "adani","ambani","musk","trump","recession"
]

RSS_FEEDS = {
    "Moneycontrol":"https://www.moneycontrol.com/rss/business.xml",
    "EconomicTimes":"https://economictimes.indiatimes.com/markets/rssfeeds/1977021501.cms",
    "Reuters":"https://www.reutersagency.com/feed/?best-topics=business-finance&post_type=best",
    "CNBC":"https://www.cnbc.com/id/10001147/device/rss/rss.html"
}


# ============================================================
# NEWS SYSTEM
# ============================================================

def fetch_market_news(ticker):

    symbol = ticker.replace(".NS","")
    symbol_lower = symbol.lower()

    company = []
    macro = []

    for source, url in RSS_FEEDS.items():
        try:
            feed = feedparser.parse(url)

            for entry in feed.entries[:50]:

                title = entry.title.lower()
                summary = entry.get("summary", "").lower()

                # Check both title and summary
                if symbol_lower in title or symbol_lower in summary:
                    company.append({
                        "title": entry.title,
                        "link": entry.link
                    })

                elif any(k in title for k in HIGH_IMPACT):
                    macro.append({
                        "title": entry.title,
                        "link": entry.link
                    })

        except:
            continue

    return company, macro


def sentiment_score(news_list):

    if len(news_list) == 0:
        return 0

    scores=[]
    for n in news_list[:5]:
        inputs = tokenizer(n["title"], return_tensors="pt", truncation=True)
        out = model_nlp(**inputs)
        p = torch.softmax(out.logits, dim=1)[0].tolist()
        scores.append(p[2]-p[0])

    return np.mean(scores)


def weighted_sentiment(company, macro):
    comp = sentiment_score(company)
    mac = sentiment_score(macro)
    final = (0.7*comp) + (0.3*mac)
    return final

# ============================================================
# TECHNICAL FEATURES
# ============================================================

def load_features(ticker):

    df = yf.download(ticker, period="3y", auto_adjust=False, progress=False)

    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)

    df = df[['Open','High','Low','Close','Volume']].dropna()
    close = df['Close']

    df['RSI'] = ta.momentum.RSIIndicator(close).rsi()
    macd = ta.trend.MACD(close)
    df['MACD'] = macd.macd()
    df['MACD_signal'] = macd.macd_signal()
    df['MA50'] = close.rolling(50).mean()
    df['MA200'] = close.rolling(200).mean()
    df['VOL_MA'] = df['Volume'].rolling(20).mean()
    df['Return'] = close.pct_change()

    return df.dropna()


# ============================================================
# CORE ML ENGINE
# ============================================================

def model_prediction(df, sentiment):

    df['Target'] = (df['Return'].shift(-1) > 0.004).astype(int)

    features = df[['RSI','MACD','MACD_signal','MA50','MA200','VOL_MA']].copy()
    features.loc[:, 'sentiment'] = sentiment

    X = features[:-1]
    y = df['Target'][:-1]

    split = int(len(X)*0.8)

    model = RandomForestClassifier(
        n_estimators=300,
        random_state=42
    )

    model.fit(X[:split], y[:split])
    prob = model.predict_proba(X.iloc[-1:])[0][1]

    return prob

# ============================================================
# INDEX FETCHER (50 / 100 / 150 / 250 / 500)
# ============================================================

def get_index(index_name="NIFTY 50"):

    try:
        headers = {"User-Agent": "Mozilla/5.0"}
        url = f"https://www.nseindia.com/api/equity-stockIndices?index={index_name.replace(' ','%20')}"
        data = requests.get(url, headers=headers, timeout=5).json()

        symbols = []

        for d in data["data"]:
            sym = d.get("symbol")

            # Skip only actual index rows
            if sym and sym != "NIFTY":
                symbols.append(sym + ".NS")

        return symbols

    except Exception:
        print("⚠ API fetch failed. Using fallback list.")
        return [
            "RELIANCE.NS","TCS.NS","INFY.NS","HDFCBANK.NS","ITC.NS",
            "LT.NS","SBIN.NS","AXISBANK.NS","ICICIBANK.NS","WIPRO.NS"
        ]

# ============================================================
# MARKET SCANNER
# ============================================================

from concurrent.futures import ThreadPoolExecutor

def scan_market(index_name="NIFTY 50", limit=None):

    stocks = get_index(index_name)

    if limit:
        stocks = stocks[:limit]

    results = []

    print(f"\n🔍 Scanning {index_name} ({len(stocks)} stocks)...")

    def check(stock):
        try:
            df = load_features(stock)
            if df is None or len(df) < 200:
                return

            company, macro = fetch_market_news(stock)
            sent = weighted_sentiment(company, macro)

            prob = model_prediction(df, sent)

            results.append((stock, round(prob*100,2)))

        except:
            pass

    with ThreadPoolExecutor(max_workers=6) as executor:
        executor.map(check, stocks)

    if len(results) == 0:
        print("No valid stocks scanned.")
        return

    # Sort entire market by bullish probability
    ranked = sorted(results, key=lambda x: x[1])

    print("\n==============================")
    print("MARKET RANKING RESULTS")
    print("==============================")

    print("\n🟢 TOP MOST BULLISH STOCKS:")
    top_n = top_dropdown.value
    for stock, prob in ranked[-top_n:][::-1]:
        print(f"• {stock} | Bullish Probability: {prob}%")

    print("\n🔴 TOP MOST BEARISH STOCKS:")
    for stock, prob in ranked[:top_n]:
        bearish_strength = round(100 - prob, 2)
        print(f"• {stock} | Bearish Strength: {bearish_strength}%")

    return None

# ============================================================
# DEEP STOCK RESEARCH
# ============================================================

def deep_research(ticker):
    report = {}

    df = load_features(ticker)
    latest = df.iloc[-1]

    trend = "UPTREND" if latest['MA50'] > latest['MA200'] else "DOWNTREND"
    rsi = round(latest['RSI'], 2)
    volatility = round(df['Return'].std() * 100, 2)
    volatility_str = f"{volatility}%"

    report['technical'] = {
        "trend": trend,
        "rsi": float(rsi),
        "volatility": volatility_str
    }

    company, macro = fetch_market_news(ticker)
    sent = weighted_sentiment(company, macro)

    prob = model_prediction(df, sent)

    company_news = []
    if company:
        for n in company[:3]:
            snippet = fetch_article_snippet(n["link"])
            company_news.append({
                "title": n['title'],
                "snippet": snippet,
                "link": n['link']
            })
    
    macro_news = []
    if macro:
        for n in macro[:3]:
            macro_news.append({
                "title": n['title'],
                "link": n['link']
            })

    report['news_analysis'] = {
        "company_specific": company_news if company_news else [],
        "market_macro": macro_news if macro_news else []
    }

    signal = "SIDEWAYS"
    if prob > 0.6:
        signal = "BULLISH SWING"
    elif prob < 0.4:
        signal = "BEARISH SWING"

    report['ai_probability'] = {
        "bullish_probability": f"{round(prob * 100, 2)}%",
        "signal": signal
    }

    price = latest['Close']
    report['swing_plan'] = {
        "entry": round(price, 2),
        "stoploss": round(price * 0.97, 2),
        "target": round(price * 1.05, 2)
    }

    return report

def scan_market(index_name="NIFTY 50", limit=None, top_n=10):
    stocks = get_index(index_name)

    if limit:
        stocks = stocks[:limit]

    results = []

    def check(stock):
        try:
            df = load_features(stock)
            if df is None or len(df) < 200:
                return

            company, macro = fetch_market_news(stock)
            sent = weighted_sentiment(company, macro)
            prob = model_prediction(df, sent)
            results.append((stock, round(prob * 100, 2)))
        except Exception as e:
            print(f"Error processing {stock}: {e}")

    with ThreadPoolExecutor(max_workers=6) as executor:
        executor.map(check, stocks)

    if not results:
        return {
            "scan_details": {
                "index": index_name,
                "stocks_scanned": 0
            },
            "top_most_bullish_stocks": [],
            "top_most_bearish_stocks": []
        }

    ranked = sorted(results, key=lambda x: x[1], reverse=True)

    top_bullish = [{"stock": str(stock), "bullish_probability": f"{prob}%"} for stock, prob in ranked[:top_n]]
    
    ranked_bearish = sorted(results, key=lambda x: x[1])
    top_bearish = [{"stock": str(stock), "bearish_strength": f"{round(100 - prob, 2)}%"} for stock, prob in ranked_bearish[:top_n]]

    return {
        "scan_details": {
            "index": index_name,
            "stocks_scanned": len(results)
        },
        "top_most_bullish_stocks": top_bullish,
        "top_most_bearish_stocks": top_bearish
    }
